### PR TITLE
Adds a testbench

### PR DESCRIPTION
**Pull request by mightyiam**
Demos are better than words so checkout this branch and then

```sh
$ node package.js
$ npm install
$ npm run start-testbench-server
```

And open your browser at `http://localhost:8888` (I intend to replace this hard coded port with a [dynamically chosen one](https://www.npmjs.com/package/portfinder)).

Played with it a bit?

This is useful for manual debugging and testing and also for the future automated browser functional testing (I'm currently thinking [Nightwatch.js](http://nightwatchjs.org/)).

It can also be a basis for a pretty demo on a public site.

### CODE REVIEW

**Comment by winhamwr** [comment]
Is there a reason you went with this instead of a grunt/gulp server?

I'm +0

**Comment by winhamwr** [comment]
Nightwatch.js looks pretty cool!

**Comment by mightyiam** [comment]
Grunt is for tasks with dependencies, if you ask me. I don't seem to have anything to justify that, in this project.

Gulp is for building with assets, if you ask me and I don't see anything like that, as well.

**Comment by mightyiam** [comment]
Thank you!

**Pull request merged**
